{
 "title": "Weather",
 "tags": [ "Weather" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Humidity Garage Inside",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"humidity\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"pinnum\"::tag = '3') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Garage Inside DHT22",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Humidity (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "pinnum::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "Temperature (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "pinnum::tag", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Garage Inside",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"temperature\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"pinnum\"::tag = '3') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Pressure Garage Inside",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pressure\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"sensor_type_name\"::tag = 'bmp280') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Garage Inside BMP280",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 14 },
   "targets": [
    {
     "alias": "Pressure (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "query": "SELECT mean(\"pressure\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"sensor_type_name\"::tag = 'bmp280') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "sensor_type_name::tag", "operator": "=", "value": "bmp280" }
     ]
    },
    {
     "alias": "Temperature (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "sensor_type_name::tag", "operator": "=", "value": "bmp280" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Garage Inside",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"temperature\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"sensor_type_name\"::tag = 'bmp280') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Humidity Garage Outside",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"humidity\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"pinnum\"::tag = '15') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Garage Outside DHT22",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 28 },
   "targets": [
    {
     "alias": "Humidity (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "pinnum::tag", "operator": "=", "value": "15" }
     ]
    },
    {
     "alias": "Temperature (stork)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "stork" },
      { "condition": "AND", "key": "pinnum::tag", "operator": "=", "value": "15" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Garage Outside",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"temperature\") FROM \"Weather\" WHERE (\"host\"::tag = 'stork' AND \"pinnum\"::tag = '15') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}